### ISSUE TITLE
Redirect after progress is done

### ISSUE THREAD

**Issue by yeamusic21** [djdmorrison/flask-progress-example#5]
Love this example!  Super simple and light weight.  Any thoughts on how to get it to redirect to another page when the progress is done (that doesn't involve user interaction)?

**Comment by djdmorrison** [comment]
Thanks! On [line 15 of index.html](https://github.com/djdmorrison/flask-progress-example/blob/master/templates/index.html#L15), after the `source.close()` you could add `window.location.replace("/finished");`.

**Comment by yeamusic21** [comment]
That worked like a charm!  Thanks so much and you rock! :-D

**Comment by yeamusic21** [comment]
closing issue based on [comment](https://github.com/djdmorrison/flask-progress-example/issues/5#issuecomment-571587210)
